version: '2'
services:
  openvpn:
    build: build/openvpn/.
    volumes:
     - ./configs/openvpn/conf:/etc/openvpn
    container_name: openvpn
    hostname: vpnoffice.smart-uk.ru
    #network_mode: host
    ports:
     - "1194:1194/udp"
     - "1194:1194"
    restart: always
    cap_add:
     - NET_ADMIN

